Repository utah-aba-finder/utah-aba-finder-fe, pull requests merged in 2024-08, with the labels that each got.

#16 iteration0/basic-structure-completed+Assets-uploaded
  src/App.test.tsx
  src/App/App.css
  src/App/App.tsx
  src/Assets/Logo.png
  src/Assets/children-banner.jpg
  src/Assets/family-icon.png
  src/Assets/information-banner.jpg
  src/Assets/insurance-banner.jpg
  src/Assets/insurance-icon.png
  src/Assets/insurance-pic.jpg
  src/Assets/map-icon.png
  src/Assets/puzzle-icon.png
  src/Assets/screening-banner.jpg
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
  src/Information-page/InformationPage.css
  src/Information-page/InformationPage.tsx
  src/Login-page/LoginPage.css
  src/Login-page/LoginPage.tsx
  src/Providers-page/ProvidersPage.css
  src/Providers-page/ProvidersPage.tsx
  src/Screening-page/ScreeningPage.css
  src/Screening-page/ScreeningPage.tsx
  src/index.css
  src/index.tsx
Labels: structure-setup, TypeScript

#19 iteration0/FE/feat-added header and footer
  src/Footer/Footer.css
  src/Footer/Footer.tsx
Labels: structure-setup, TypeScript

#20 added initial routes for current pages
  Docs/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/App/App.tsx
  src/index.tsx
Labels: TypeScript

#21 added header and footer
  src/App/App.css
  src/Assets/menu-icon.png
  src/Footer/Footer.css
  src/Footer/Footer.tsx
  src/Header/Header.css
  src/Header/Header.tsx
  src/Homepage/Homepage.tsx
Labels: Design

#22 Created main screening page and initially started separate test pages
  public/UAL_logo.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/App/App.tsx
  src/Screening-page/ScreeningPage.css
  src/Screening-page/ScreeningPage.tsx
  src/Screening1/Screening1.css
  src/Screening1/Screening1.tsx
  src/Screening2/Screening2.css
  src/Screening2/Screening2.tsx
  src/Utility/Types.ts
  src/logo.svg
Labels: Design

#23 Iteration1/feat/homepage+adding sections
  src/App/App.css
  src/App/App.tsx
  src/Assets/utah.jpg
  src/Header/Header.css
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
Labels: Design, TypeScript

#25 Iteration1/FE/homepage component setup
  src/Assets/NewLogo.png
  src/Assets/NewLogo2.png
  src/Assets/NewLogo3.png
  src/Assets/Utah-Background.jpg
  src/Assets/menu-icon2.png
  src/Assets/spanish-pic.jpg
  src/Assets/utah2.jpg
  src/Footer/Footer.css
  src/Header/Header.tsx
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
Labels: structure-setup, Design

#30 adjusted font size for all pages
  src/Header/Header.tsx
  src/Information-page/InformationPage.css
  src/Information-page/InformationPage.tsx
  src/Providers-page/ProvidersPage.css
  src/Providers-page/ProvidersPage.tsx
  src/Screening-page/ScreeningPage.css
Labels: structure-setup, Design, TypeScript

#46 Iteration1/feat/provider page styling
  src/Providers-page/ProvidersPage.css
  src/Providers-page/ProvidersPage.tsx
  src/Providers-page/SearchBar.css
  src/Providers-page/SearchBar.tsx
  src/Providers-page/klay.png
Labels: Design, TypeScript

#47 Iteration3/FE/feat/contact us
  package-lock.json
  package.json
  src/App/App.tsx
  src/Assets/team-banner.webp
  src/ContactUs/ContactUs.css
  src/ContactUs/ContactUs.tsx
  src/Header/Header.css
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
Labels: Design, TypeScript, Accessibility

#50 iteration3/FE/feat/Styling changes for better mobile view
  src/ContactUs/ContactUs.css
  src/Homepage/Homepage.css
  src/Information-page/InformationPage.css
  src/Providers-page/ProvidersPage.css
  src/Screening-page/ScreeningPage.css
  src/Signup/Signup.tsx
Labels: Design

#52 updated media quieries for login and sign up pages
  src/Provider-login/LoginPage.css
  src/Provider-login/LoginPage.tsx
  src/Signup/Signup.css
Labels: Design

#59 Login page/jw
  src/Signup/Signup.css
  src/Signup/Signup.tsx
Labels: structure-setup, Design

#58 iteration3/FE/made minor changes for banner font size to be uniformed
  src/ContactUs/ContactUs.css
  src/Homepage/Homepage.css
  src/Provider-login/LoginPage.css
  src/Providers-page/ProvidersPage.css
  src/Screening-page/ScreeningPage.css
Labels: Design

#60 404page
  src/Assets/404Image.png
  src/PageNotFound/PageNotFound.css
  src/PageNotFound/PageNotFound.tsx
  src/Signup/Signup.css
Labels: Design

#61 iteration3/FE/modal styling
  src/AboutUs/AboutUs.tsx
  src/Providers-page/ProviderModal.css
  src/Providers-page/ProviderModal.tsx
Labels: Design

#62 Other/adding profile pic
  src/AboutUs/AboutUs.tsx
  src/Assets/jordan-pic.jpg
  src/Assets/kevin-pic.png
  src/Providers-page/ProviderModal.css
  src/Providers-page/ProviderModal.tsx
Labels: TypeScript
