Repository utah-aba-finder/utah-aba-finder-fe, pull requests merged in 2024-11, with the labels that each got.

#192 frontend side of donations page created
  package-lock.json
  package.json
  src/Donations/CheckoutForm.tsx
  src/Donations/Donations.css
  src/Donations/Donations.tsx
Labels: Design, TypeScript, Functionality

#194 Updated providers page/jw
  public/ASL_logo.png
  public/index.html
  src/AboutUs/AboutUs.css
  src/AboutUs/AboutUs.tsx
  src/Assets/autismserviceslocator_logo.png
  src/Assets/flourHeart.jpg
  src/Assets/wansutter.png
  src/Assets/williamsonFamily.jpeg
  src/Footer/Footer.css
  src/Footer/Footer.tsx
  src/Header/Header.tsx
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
  src/Providers-page/ProvidersPage.tsx
  src/Providers-page/SearchBar.css
  src/Providers-page/SearchBar.tsx
Labels: structure-setup

#195 fixed styling issues for the what we're about on the homepage
  package-lock.json
  package.json
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
Labels: Design
