Repository utah-aba-finder/utah-aba-finder-fe, pull requests merged in 2024-09, with the labels that each got.

#68 cypress specs created for testing
  cypress.config.ts
  cypress/e2e/aboutus.cy.ts
  cypress/e2e/casttest.cy.ts
  cypress/e2e/contactus.cy.ts
  cypress/e2e/footer.cy.ts
  cypress/e2e/header.cy.ts
  cypress/e2e/homepage.cy.ts
  cypress/e2e/informationpage.cy.ts
  cypress/e2e/pagenotfound.cy.ts
  cypress/e2e/provider-login.cy.ts
  cypress/e2e/providerspage.cy.ts
  cypress/e2e/screeningpage.cy.ts
  cypress/e2e/signuppage.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/Header/Header.css
  src/Header/Header.tsx
  src/Homepage/Homepage.tsx
Labels: Cypress testing

#69 cypress testing for the screening page and CASt test
  cypress/e2e/casttest.cy.ts
  cypress/e2e/pagenotfound.cy.ts
  cypress/e2e/provider-login.cy.ts
  cypress/e2e/screeningpage.cy.ts
  cypress/e2e/signuppage.cy.ts
  src/Provider-login/LoginPage.tsx
  src/Screening-page/ScreeningPage.tsx
  src/Screening2/Screening2.tsx
  tsconfig.json
Labels: Cypress testing

#70 enhanced accessibility + cypress tests
  cypress/e2e/header.cy.ts
  cypress/e2e/homepage.cy.ts
Labels: Cypress testing, Accessibility

#72 added cypress tests
  cypress/e2e/aboutus.cy.ts
  cypress/e2e/contactus.cy.ts
  cypress/e2e/footer.cy.ts
  cypress/e2e/homepage.cy.ts
  cypress/e2e/informationpage.cy.ts
  src/ContactUs/ContactUs.css
  src/Header/Header.tsx
  src/Homepage/Homepage.css
  src/Homepage/Homepage.tsx
Labels: Cypress testing

#74 added edit-page
  src/App/App.tsx
  src/Provider-edit/CountiesModal.css
  src/Provider-edit/CountiesModal.tsx
  src/Provider-edit/InsuranceModal.css
  src/Provider-edit/InsuranceModal.tsx
  src/Provider-edit/ProviderEdit.css
  src/Provider-edit/ProviderEdit.tsx
Labels: TypeScript

#79 Iteration5/fe/cypress adjustments
  cypress/e2e/pagenotfound.cy.ts
  src/Provider-edit/ProviderEdit.tsx
Labels: Cypress testing

#84 added error message for non-displaying providers
  src/Providers-page/ProvidersPage.tsx
Labels: error handling

#85 updated isurance modal and county modal to render already accepted op…
  src/Provider-edit/CountiesModal.tsx
  src/Provider-edit/InsuranceModal.css
  src/Provider-edit/InsuranceModal.tsx
  src/Provider-edit/ProviderEdit.tsx
  src/Utility/Types.ts
Labels: Functionality

#108 adjusted navbar height and for media view
  src/App/App.tsx
  src/Header/Header.css
  src/Header/Header.tsx
  src/Resources/Resources.css
  src/Resources/Resources.tsx
Labels: Design

#115 added profile pics and adjustments for styling
  src/AboutUs/AboutUs.css
  src/AboutUs/AboutUs.tsx
  src/Assets/austin-pic.png
  src/Assets/chee-pic.png
Labels: Design, TypeScript

#118 added overflow hidden and fixed the issue
  src/Homepage/Homepage.css
Labels: bug
